In [17]:
import numpy as np
add_div = 5

x = np.array([[0,1,2],
             [3,4,5],
             [6,7,8],
             [9,10,11]])
ret = np.empty((0, x.shape[1], add_div),int)
for i in x:
  tmp = np.empty((0, add_div), int)

  for j in i:
    tmp2 = []

    for k in range(add_div):
      tmp2.append(j)

    tmp2 = np.array(tmp2)
    tmp2 = tmp2.reshape((1,add_div))

    tmp = np.append(tmp, tmp2, axis=0)

  tmp = tmp.reshape((1, x.shape[1], add_div))
  ret = np.append(ret,tmp,axis=0)
print(ret[:,:,0])


(1, 3, 5)
(0, 3, 5)
(1, 3, 5)
(1, 3, 5)
(1, 3, 5)
(2, 3, 5)
(1, 3, 5)
(3, 3, 5)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
